services:
  crudflask2:
    image: crudflask2
    build:
      context: ./crud
    container_name: crudflask2
    environment:
      - MYSQL_USER=${CRUD_USER}
      - MYSQL_PASSWORD=${CRUD_PASS}
      - MYSQL_DB=${CRUD_DB}
      - MYSQL_HOST=${MARIADB_SERVER}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    ports:
      - "8001:8001"   
    networks:
      proxy:
        aliases:
          - crudflask2
    restart: unless-stopped
networks:
  proxy:
    external: true
    name: proxy
